source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.2', '>= 4.2.6'
gem 'dalli'
# Use sqlite3 as the database for Active Record
group :development, :test do
  gem 'mysql2', '~> 0.4.4'
end
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
#gem 'sass-rails', '3.2.3'
# setup our services
#gem "eme_services_client", "~> 0.0.3", :git => "git@github.com:enmasse-entertainment/eme_services_client.git"
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
#gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
#gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# language support
gem 'refinerycms-i18n'

# Use ActiveModel has_secure_password
#gem 'bcrypt','~>3.1.11'

# Use Unicorn as the app server
# gem 'unicorn'
#gem 'puma'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end


gem "api_consumer", "~> 0.0.6"

# AMS API Client
#gem "eme-ams-api-client", '~> 1.0.3', :git => "https://github.com/refinery/eme-ams-api-client.git", :require => 'ams_api_client'

gem 'rest-client', :require => false


# Refinery CMS
gem 'refinerycms'
#gem 'refinerycms', '~> 2.1.0'

# Optionally, specify additional Refinery CMS Extensions here:
#gem 'refinerycms-acts-as-indexed', ['~> 2.0', '>= 2.0.1']
#gem 'refinerycms-wymeditor', ['~> 1.0', '>= 1.0.6']
#gem 'refinerycms-authentication-devise', '~> 1.0'
gem 'refinerycms-authentication-devise', '~> 1.0', '>= 1.0.4'

gem 'refinerycms-settings', '~> 3.0'
gem 'refinerycms-wymeditor'
gem 'refinerycms-blog', git: 'https://github.com/refinery/refinerycms-blog', branch: 'master'
#gem 'refinerycms-blog', github: 'refinery/refinerycms-blog', ref: "d891009d8b26cbccfc7fcdec645e1e2382c641bc"
#gem 'refinerycms-blog', ['~> 3.0', '>= 3.0.0']
#  gem 'refinerycms-inquiries', ['~> 3.0', '>= 3.0.0']
#  gem 'refinerycms-search', ['~> 3.0', '>= 3.0.0']
#  gem 'refinerycms-page-images', ['~> 3.0', '>= 3.0.0']
gem 'acts_as_indexed', '~> 0.8.3'
gem "refinerycms-widgets"

gem 'eme_api_consumer', '0.0.10', git: 'https://github.com/enmasse-entertainment/eme_api_consumer', branch: 'spam-hotfix'
gem 'eme_services_client', '~> 0.0.3', :git => 'https://82e2ef820014e7605ba62d7a8fc7c087bfcc493f:x-oauth-basic@github.com/enmasse-entertainment/eme_services_client.git'
gem 'eme_global_assets', '0.6.2', :git => 'https://82e2ef820014e7605ba62d7a8fc7c087bfcc493f:x-oauth-basic@github.com/enmasse-entertainment/eme_global_assets.git'

gem 'puma'

gem 'httparty'

gem 'twitch-api'