---
ams_api:
  ams:
    base_url: 'https://account-edge2.enmasse.com'
    auth_token: "ef29bf65f9096bf682ddadff868ca14b"
  facebook:
    id: YOUR_FB_ID
    secret: YOUR_FB_SECRET
  vip:
    active: true
    exp_factor: 1
    token_factor: 0.1
