gifting:
  enabled: true
  url: "https://account-edge.enmasse.com"
  ssl: true
  name: "Gifting"
  auth_key: "Token token=ef29bf65f9096bf682ddadff868ca14b"
  use_memcache: true
  memcache_hosts:
    - "localhost:11211"
  cache_prefix: "gifting-dev"
  #promotion_id: 70
  #gift_kind_id: 4
  type: json

  tera:
    enabled: true
    promotion_id: 70
    gift_kind_id: 4

  kritika:
    enabled: true
    promotion_id: 363
    gift_kind_id: 11

  closers:
    enabled: true
    promotion_id: 353
    gift_kind_id: 9

  ava:
    enabled: true
    promotion_id: 356
    gift_kind_id: 10

  potion_shack:
    enabled: false
    red_group_promo_code: 25678
    group_promo_code: 1245
    catalysts_per_try: 5