item_delivery:
  url: "https://account-edge.enmasse.com"
  ssl: true
  name: "ItemDelivery"
  auth_key: "Token token=ef29bf65f9096bf682ddadff868ca14b"
  use_memcache: false
  group_codes:
    26: steamemp10
    27: steamemp20
    28: steamemp40
    29: steamemp100
  type: json
