FROM ubuntu:16.04

#RUN echo 'deb http://repo.percona.com/apt xenial testing' > /etc/apt/sources.list.d/percona-release.list

RUN  echo 'Acquire::http { Proxy "http://10.64.74.30:3142"; };' >> /etc/apt/apt.conf.d/01proxy

RUN { \
      echo percona-server-server-5.6 percona-server-server/root_password password 'unused'; \
      echo percona-server-server-5.6 percona-server-server/root_password_again password 'unused'; \
   } | debconf-set-selections

RUN apt-get update && apt-get install -y wget && \
    wget "https://repo.percona.com/apt/percona-release_0.1-4.xenial_all.deb" && \
    dpkg -i percona-release_0.1-4.xenial_all.deb && \
    apt-get update && \
    apt-get install -y \
    percona-server-server-5.6

CMD ["mysqld"]
