const baseAgeApi = 'https://service-dev.ageofempires.com/api';
const modsApi = 'https://api-dev.ageofempires.com/api/v1/mods';
const modsApiV4 = 'https://api-dev.ageofempires.com/api/v4/mods';
//const bugsApi = 'http://localhost:5000/api/v1/bugs';
const bugsApi = 'https://api-dev.ageofempires.com/api/v1/bugs';

const wordpressAjax = '/wp-admin/admin-ajax.php'; // TODO -- Strip out directory from url

const baseStatsApi = 'https://stats.ageofempires.com/api';
const baseStatsV2Api = 'https://age-stats-dev.azurewebsites.net/api/v2';
const baseV2Api = 'https://api-dev.ageofempires.com/api/v2';

// For Age III DE Stats
const baseStatsApiDev = 'https://api-dev.ageofempires.com/api';

const config = {
  api: {    
    baseStatsApi,
    baseStatsV2Api,
    baseV2Api,
    baseStatsApiDev,
    clansAction: `${wordpressAjax}?action=clanActions`,
    clansFlag: `${wordpressAjax}?action=clanFlag`,
    clansApplicantsList: `${wordpressAjax}?action=applicants`,
    clansBlockedList: `${wordpressAjax}?action=blocked`,
    clansMembersList: `${wordpressAjax}?action=members`,
    clansMemberProfile: `${wordpressAjax}?action=clansMemberProfile`,
    clansSearchFilters: `/wp-content/plugins/Clubs/scripts/json/clansSearchFilters.json`,
    clansSearchResults: `${wordpressAjax}?action=clans`,
    modsFind: `${modsApi}/FindAsUser`,
    modsInstall: `${modsApi}/Install`,
    modsInstalled: `${modsApi}/Installed`,
    modsUninstall: `${modsApi}/Uninstall`,
    modsMine: `${modsApi}/My`,
    modsAnonDetail: `${modsApi}/AnonDetail`,
    modsDetail: `${modsApi}/Detail`,
    modsDownload: `${modsApi}/Download`,
    modsLike: `${modsApi}/Like`,
    modsFlag: `${modsApi}/Flag`,
    modsTypes: `${modsApi}/Types`,
    modsTags: `${modsApi}/Tags`,
    modsCreate: `${modsApi}/Create`,
    modsEdit: `${modsApi}/Edit`,
    modsDelete: `${modsApi}/Delete`,
    modsFlagged: `${modsApi}/GetFlagged`,
    modsFlaggedDetail: `${modsApi}/GetFlaggedDetail`,
    modsModerate: `${modsApi}/Moderate`,
    bugCreate: `${bugsApi}/Submit`,
    bugGetList: `${bugsApi}/GetList`,
    bugGetDetail: `${bugsApi}/BugDetail`,
    bugUpdate: `${bugsApi}/UpdateBug`,
    bugGetAsset: `${bugsApi}/GetAsset`,
    games: `${baseAgeApi}/Games`,
    clans: `${wordpressAjax}?action=clans`,
    ClansCheckExisting: `${wordpressAjax}?action=clans_check_exists`,
    ClansCheckExistingClan: `${wordpressAjax}?action=clans_clan_exists`,
    clansDetail: `${wordpressAjax}?action=clans&paged=1&postsPerPage=1`,
    clansSave: `${wordpressAjax}?action=clans_save`,
    clansEdit: `${wordpressAjax}?action=clans_edit`,
    clubReserve: `${wordpressAjax}?action=club_reserve`,
    clansLogoBgs: `${baseAgeApi}/clans/GetImages?key=logo_backgrounds`,
    clansLogoShields: `${baseAgeApi}/clans/GetImages?key=logo_shields`,
    clansLogoIcons: `${baseAgeApi}/clans/GetImages?key=logo_icons`,
    clansBgs: `${baseAgeApi}/clans/GetImages?key=background_images`,
    CountryList: 'https://webapi.ageofempires.com/api/CountryList',
    TwitterFeed: 'https://webapi.ageofempires.com/api/Twitter',
    campaignStats: `${baseStatsApi}/AgeDE/GetCampaign`,
    Age2campaignStats: `${baseStatsApi}/v2/AgeII/GetCampaign`,
    SPFull: `${baseStatsApi}/AgeDE/GetSPFull`,
    MPFull: `${baseStatsApi}/AgeDE/GetMPFull`,
    Age2MPFull: `${baseStatsV2Api}/AgeII/GetMPFull`,
    Age2SPFull: `${baseStatsApi}/AgeII/GetSPFull`,
    MPMatchList: `${baseStatsApi}/AgeDE/getmpmatchlist`,
    SPMatchList: `${baseStatsApi}/AgeDE/getspmatchlist`,
    Age2MPMatchList: `${baseStatsV2Api}/AgeII/GetMPMatchList`,
    Age2SPMatchList: `${baseStatsApi}/AgeII/GetSPMatchList`,
    validateGamertag: `${baseAgeApi}/ValidateUserName`,
    getMatchDetail: `${baseStatsApi}/AgeDE/getmatchdetail`,
    getAge2MatchDetail: `${baseStatsV2Api}/AgeII/GetMPMatchDetail`,
    getAge2MatchReplay: `https://aoe.ms/replay`,  
    languages: `${baseAgeApi}/Languages?gameId=aoe`,
  },
  apiV4: {
      modsFind: `${modsApiV4}/Find`,
      modsInstall: `${modsApiV4}/Subscribe`,
      modsInstalled: `${modsApiV4}/Installed`,
      modsUninstall: `${modsApiV4}/UnSubscribe`,
      modsMine: `${modsApiV4}/My`,      
      modsDetail: `${modsApiV4}/Detail/`,      
      modsLike: `${modsApiV4}/Like`,
      modsFlag: `${modsApiV4}/Report`,
      modsTypes: `${modsApiV4}/Types`,
      modsTags: `${modsApiV4}/Tags`,
      modsPublish: `${modsApiV4}/Publish`,
      modsPublishFile: `${modsApiV4}/PublishFile`,
      modsDelete: `${modsApiV4}/Delete`,
      modsFlagged: `${modsApiV4}/GetFlagged`,
      modsFlaggedDetail: `${modsApiV4}/GetFlaggedDetail`,
      modsModerate: `${modsApiV4}/Moderate`,
      games: `${baseAgeApi}/Games`,
  },
  events: {
    onClansSearch: 'onClansSearch',
    onClansSearchResults: 'onClansSearchResults',
    onPagination: 'onPagination',
  },
  hasTouch: Boolean('ontouchstart' in window || navigator.maxTouchPoints || navigator.msMaxTouchPoints),
  isMobileDevice: window.wp_object.devices.isMobile,
  userLoggedIn: window.wp_object.user_logged_in.status,
  acctType: window.wp_object.acctType,
};
export default config;
