FROM agescentral.azurecr.io/wordpressbase:v1
# ========
# ENV vars
# ========

ARG SITE_NAME
ARG ARTIFACT
ARG SITE_CONFIG_REPO
ARG BUILD_ID

#php
#/usr/local/etc/php/php.ini
ENV PHP_HOME "/usr/local/etc/php"
ENV PHP_CONF_DIR $PHP_HOME
ENV PHP_CONF_FILE $PHP_CONF_DIR"/php.ini"

# wordpress install and common plugins
RUN git clone --depth 1 -b master https://weweb:donmutssfrtah7edpkfzmuwwkbxp2tuxtgrlj5vpauf2wbq5f4mq@dev.azure.com/weweb/$SITE_NAME/_git/$SITE_CONFIG_REPO /var/www/tmp/ \
&& cp -v -R /var/www/tmp/content/* /var/www/html/ \
&& cp -v -R /var/www/tmp/nginx/* /etc/nginx/ \
&& cp -v /var/www/tmp/fpm/www.conf /usr/local/etc/php-fpm.d/ \
&& cp -v $PHP_HOME"/php.ini-production" $PHP_CONF_FILE \
&& cp -v /var/www/tmp/content/.htaccess /var/www/html/ \
&& cp -v /var/www/tmp/content/.user.ini /var/www/html/ \
&& mv /var/www/html/wp-content/plugins/Clubs/inc/Utilities /var/www/html/wp-content/plugins/Clubs/inc/utilities \
&& rm /usr/local/etc/php-fpm.d/zz-docker.conf \
&& rm -rf /var/www/html/.git \
&& rm -rf /var/www/tmp \
&& echo $BUILD_ID > /var/www/build_$BUILD_ID.log

# site specific content (theme, wp-config, plugins, etc.)
WORKDIR $ARTIFACT
COPY / /var/www/html/wp-content/themes/msgpwebteam/

RUN cd /var/www/html/wp-content/themes/msgpwebteam/ \
&& rm DockerFile \
&& composer update \
#&& apk add dos2unix \
#&& find /var/www/html/ -type f -print0 | xargs -0 dos2unix \
#&& apk del dos2unix \
&& chown -R www-data:www-data /var/www/html/ \
&& chown -R www-data:www-data /var/lib/nginx/ \
&& find /var/www/html/ -type f -exec chmod 664 {} \; \
&& find /var/www/html/ -type d -exec chmod 775 {} \; \
&& ln -s /etc/nginx/sites-available/$SITE_NAME /etc/nginx/sites-enabled/$SITE_NAME \
&& chmod 777 /var/www/html/wp-content/cache \
&& chmod 777 /var/www/html/wp-content/w3tc-config 

EXPOSE 80 2222  

ENTRYPOINT ["entrypoint.sh"]
