module GeoIpHelper

  def self.STATES
    [
      [ "-- Non-US --", "--" ],
      [ "Alabama", "AL" ], 
      [ "Alaska", "AK" ], 
      [ "Arizona", "AZ" ], 
      [ "Arkansas", "AR" ], 
      [ "California", "CA" ], 
      [ "Colorado", "CO" ], 
      [ "Connecticut", "CT" ], 
      [ "Delaware", "DE" ], 
      [ "District Of Columbia", "DC" ], 
      [ "Florida", "FL" ], 
      [ "Georgia", "GA" ], 
      [ "Hawaii", "HI" ], 
      [ "Idaho", "ID" ], 
      [ "Illinois", "IL" ], 
      [ "Indiana", "IN" ], 
      [ "Iowa", "IA" ], 
      [ "Kansas", "KS" ], 
      [ "Kentucky", "KY" ], 
      [ "Louisiana", "LA" ], 
      [ "Maine", "ME" ], 
      [ "Maryland", "MD" ], 
      [ "Massachusetts", "MA" ], 
      [ "Michigan", "MI" ], 
      [ "Minnesota", "MN" ], 
      [ "Mississippi", "MS" ], 
      [ "Missouri", "MO" ], 
      [ "Montana", "MT" ], 
      [ "Nebraska", "NE" ], 
      [ "Nevada", "NV" ], 
      [ "New Hampshire", "NH" ], 
      [ "New Jersey", "NJ" ], 
      [ "New Mexico", "NM" ], 
      [ "New York", "NY" ], 
      [ "North Carolina", "NC" ], 
      [ "North Dakota", "ND" ], 
      [ "Ohio", "OH" ], 
      [ "Oklahoma", "OK" ], 
      [ "Oregon", "OR" ], 
      [ "Pennsylvania", "PA" ], 
      [ "Rhode Island", "RI" ], 
      [ "South Carolina", "SC" ], 
      [ "South Dakota", "SD" ], 
      [ "Tennessee", "TN" ], 
      [ "Texas", "TX" ], 
      [ "Utah", "UT" ], 
      [ "Vermont", "VT" ], 
      [ "Virginia", "VA" ], 
      [ "Washington", "WA" ], 
      [ "West Virginia", "WV" ], 
      [ "Wisconsin", "WI" ], 
      [ "Wyoming", "WY" ]
    ]
  end  

  def self.COUNTRIES
    [
      [ "United States", "US" ],
      [ "Afghanistan", "AF" ],
      [ "Albania", "AL" ],
      [ "Algeria", "DZ" ],
      [ "American Samoa", "AS" ],
      [ "Andorra", "AD" ],
      [ "Angola", "AO" ],
      [ "Anguilla", "AI" ],
      [ "Antigua and Barbuda", "AG" ],
      [ "Argentina","AR" ],
      [ "Armenia", "AM" ],
      [ "Aruba", "AW" ],
      [ "Australia", "AU" ],
      [ "Austria", "AT" ],
      [ "Azerbaijan", "AZ" ],
      [ "Bahamas", "BS" ],
      [ "Bahrain", "BH" ],
      [ "Bangladesh", "BD" ],
      [ "Barbados", "BB" ],
      [ "Belarus", "BY" ],
      [ "Belgium", "BE" ],
      [ "Belize", "BZ" ],
      [ "Benin", "BJ" ],
      [ "Bermuda", "BM" ],
      [ "Bhutan", "BT" ],
      [ "Bolivia", "BO" ],
      [ "Bosnia and Herzegovina", "BA" ],
      [ "Botswana", "BW" ],
      [ "Bouvet Island", "BV" ],
      [ "Brazil", "BR" ],
      [ "British Indian Ocean Territory", "IO" ],
      [ "Brunei Darussalam", "BN" ],
      [ "Bulgaria", "BG" ],
      [ "Burkina Faso", "BF" ],
      [ "Burundi", "BI" ],
      [ "Cambodia", "KH" ],
      [ "Cameroon", "CM" ],
      [ "Canada", "CA" ],
      [ "Cape Verde", "CV" ],
      [ "Caribean", "XI" ],
      [ "Cayman Islands", "KY" ],
      [ "Central African Republic", "CF" ],
      [ "Central America", "XC" ],
      [ "Chad", "TD" ],
      [ "Chile", "CL" ],
      [ "China", "CN" ],
      [ "Christmas Island", "CX" ],
      [ "Cocos (Keeling) Islands", "CC" ],
      [ "Colombia", "CO" ],
      [ "Comoros", "KM" ],
      [ "Congo", "CG" ],
      [ "Congo, Democratic Rep.", "CD" ],
      [ "Cook Islands", "CK" ],
      [ "Costa Rica", "CR" ],
      [ "Cote d'Ivoire", "CI" ],
      [ "Croatia", "HR" ],
      [ "Cuba", "CU" ],
      [ "Cyprus", "CY" ],
      [ "Czech Republic", "CZ" ],
      [ "Denmark", "DK" ],
      [ "Djibouti", "DJ" ],
      [ "Dominica", "DM" ],
      [ "Dominican Republic", "DO" ],
      [ "East Timor", "TP" ],
      [ "Ecuador", "EC" ],
      [ "Egypt", "EG" ],
      [ "El Salvador", "SV" ],
      [ "Equatorial Guinea", "GQ" ],
      [ "Eritrea", "ER" ],
      [ "Estonia", "EE" ],
      [ "Ethiopia", "ET" ],
      [ "Falkland Islands", "FK" ],
      [ "Faroe Islands", "FO" ],
      [ "Fiji", "FJ" ],
      [ "Finland", "FI" ],
      [ "France", "FR" ],
      [ "French Guiana", "GF" ],
      [ "French Polynesia", "PF" ],
      [ "French Southern Territories", "TF" ],
      [ "Gabon", "GA" ],
      [ "Gambia", "GM" ],
      [ "Georgia", "GE" ],
      [ "Germany", "DE" ],
      [ "Ghana", "GH" ],
      [ "Gibraltar", "GI" ],
      [ "Greece", "GR" ],
      [ "Grenada", "GD" ],
      [ "Guadeloupe", "GP" ],
      [ "Guam", "GU" ],
      [ "Guatemala", "GT" ],
      [ "Guinea", "GN" ],
      [ "Guinea-Bissau", "GW" ],
      [ "Guyana", "GY" ],
      [ "Haiti", "HT" ],
      [ "Heard Island and McDonald Islands", "HM" ],
      [ "Honduras", "HN" ],
      [ "Hong Kong", "HK" ],
      [ "Hungary", "HU" ],
      [ "Iceland", "IS" ],
      [ "India", "IN" ],
      [ "Indonesia", "ID" ],
      [ "Iran (Islamic Republic of)", "IR" ],
      [ "Iraq", "IQ" ],
      [ "Ireland", "IE" ],
      [ "Israel", "IL" ],
      [ "Italy", "IT" ],
      [ "Jamaica", "JM" ],
      [ "Japan", "JP" ],
      [ "Jordan", "JO" ],
      [ "Kazakhstan", "KZ" ],
      [ "Kenya", "KE" ],
      [ "Kiribati", "KI" ],
      [ "Korea, Democratic People's Republic", "KP" ],
      [ "Kuwait", "KW" ],
      [ "Kyrgyzstan", "KG" ],
      [ "Lao People's Democratic Republic", "LA" ],
      [ "Latin America", "XL" ],
      [ "Latvia", "LV" ],
      [ "Lebanon", "LB" ],
      [ "Lesotho", "LS" ],
      [ "Liberia", "LR" ],
      [ "Libyan Arab Jamahiriya", "LY" ],
      [ "Liechtenstein", "LI" ],
      [ "Lithuania", "LT" ],
      [ "Luxembourg", "LU" ],
      [ "Macau", "MO" ],
      [ "Madagascar", "MG" ],
      [ "Malawi", "MW" ],
      [ "Malaysia", "MY" ],
      [ "Maldives", "MV" ],
      [ "Mali", "ML" ],
      [ "Malta", "MT" ],
      [ "Mariana Islands (Northern)", "MP" ],
      [ "Marshall Islands", "MH" ],
      [ "Martinique", "MQ" ],
      [ "Mauritania", "MR" ],
      [ "Mauritius", "MU" ],
      [ "Mayotte", "YT" ],
      [ "Mexico", "MX" ],
      [ "Micronesia, Federated States of", "FM" ],
      [ "Moldova, Republic of", "MD" ],
      [ "Monaco", "MC" ],
      [ "Mongolia", "MN" ],
      [ "Montserrat", "MS" ],
      [ "Morocco", "MA" ],
      [ "Mozambique", "MZ" ],
      [ "Myanmar/Burma", "MM" ],
      [ "Namibia", "NA" ],
      [ "Nauru", "NR" ],
      [ "Nepal", "NP" ],
      [ "Netherlands", "NL" ],
      [ "Netherlands Antilles", "AN" ],
      [ "New Caledonia", "NC" ],
      [ "New Zealand", "NZ" ],
      [ "Nicaragua", "NI" ],
      [ "Niger", "NE" ],
      [ "Nigeria", "NG" ],
      [ "Niue", "NU" ],
      [ "Norfolk Island", "NF" ],
      [ "Norway", "NO" ],
      [ "Oman", "OM" ],
      [ "Pakistan", "PK" ],
      [ "Palau", "PW" ],
      [ "Panama", "PA" ],
      [ "Papua New Guinea", "PG" ],
      [ "Paraguay", "PY" ],
      [ "Peru", "PE" ],
      [ "Philipines", "PH" ],
      [ "Pitcairn Island", "PN" ],
      [ "Poland", "PL" ],
      [ "Portugal", "PT" ],
      [ "Puerto Rico", "PR" ],
      [ "Qatar", "QA" ],
      [ "Reunion", "RE" ],
      [ "Romania", "RO" ],
      [ "Russian Federation", "RU" ],
      [ "Rwanda", "RW" ],
      [ "Saint Helena", "SH" ],
      [ "Saint Kitts and Nevis", "KN" ],
      [ "Saint Lucia", "LC" ],
      [ "Saint Pierre and Miquelon", "PM" ],
      [ "Saint Vincent and the Grenadines", "VC" ],
      [ "Samoa", "WS" ],
      [ "San Marino", "SM" ],
      [ "Sao Tome and Principe", "ST" ],
      [ "Saudi Arabia", "SA" ],
      [ "Senegal", "SN" ],
      [ "Serbia and Montenegro", "CS" ],
      [ "Seychelles", "SC" ],
      [ "Sierra Leone", "SL" ],
      [ "Singapore", "SG" ],
      [ "Slovakia (Slovak Republic)", "SK" ],
      [ "Slovenia", "SI" ],
      [ "Solomon Islands", "SB" ],
      [ "Somalia", "SO" ],
      [ "South Africa", "ZA" ],
      [ "South Georgia and the south Sandwich", "GS" ],
      [ "South Korea", "KR" ],      
      [ "Spain", "ES" ],
      [ "Sri Lanka", "LK" ],
      [ "Sudan", "SD" ],
      [ "Suriname", "SR" ],
      [ "Svalbard and Jan Mayen", "SJ" ],
      [ "Swaziland", "SZ" ],
      [ "Sweden", "SE" ],
      [ "Switzerland", "CH" ],
      [ "Syrian Arab Republic", "SY" ],
      [ "Taiwan, Province of China", "TW" ],
      [ "Tajikistan", "TJ" ],
      [ "Tanzania, United Republic of", "TZ" ],
      [ "Thailand", "TH" ],
      [ "The Former Yugoslav Republic of", "MK" ],
      [ "Togo", "TG" ],
      [ "Tokelau Islands", "TK" ],
      [ "Tonga", "TO" ],
      [ "Trinidad and Tobago", "TT" ],
      [ "Tunisia", "TN" ],
      [ "Turkey", "TR" ],
      [ "Turkmenistan", "TM" ],
      [ "Turks and Caicos Islands", "TC" ],
      [ "Tuvalu", "TV" ],
      [ "Uganda", "UG" ],
      [ "Ukraine", "UA" ],
      [ "United Arab Emirates", "AE" ],
      [ "United Kingdom", "GB" ],
      [ "United States Minor Outlying Islands", "UM" ],
      [ "Uruguay", "UY" ],
      [ "Uzbekistan", "UZ" ],
      [ "Vanuatu", "VU" ],
      [ "Vatican City State (Holy See)", "VA" ],
      [ "Venezuela", "VE" ],
      [ "Viet Nam", "VN" ],
      [ "Virgin Islands (GB)", "VG" ],
      [ "Virgin Islands (US)", "VI" ],
      [ "Wallis and Futuna Islands", "WF" ],
      [ "Western Sahara", "EH" ],
      [ "Worldwide", "XZ" ],
      [ "Yemen", "YE" ],
      [ "Yugoslavia, former", "YU" ],
      [ "Zambia", "ZM" ],
      [ "Zimbabwe", "ZW" ]
    ]
  end
    
end