version: '2'
services:
  #db:
  #  build: db/
  #  ports:
  #    - "3306:3306"
  #redis:
  #  image: redis:3.2
  #  ports:
  #    - "6379:6379"
  web:
    build: .
    command: bundle install; bundle exec rails s -p 3000 -e staging -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    #depends_on:
    #  - db
    #  - redis
