source "https://rubygems.org"

gem "rake"
gem "sinatra", "1.4.4", :require => "sinatra/base"
gem "api_consumer", "~> 0.0.4", :git => "git://github.com/chrisftw/api_consumer.git"

gem "rack", "1.5.2" # lock this down
gem "rack-test", "0.6.2" # lock this down

gem 'sprockets'
gem 'sprockets-helpers'
gem "billing_adapter_interface", "0.0.7", :git => "git@github.com:enmasse-entertainment/billing_adapter_interface.git"#, :branch => "emp-adder"

gem "eme_services_client", "0.0.3", :git => "git@github.com:enmasse-entertainment/eme_services_client.git"

#gem "eme_global_assets", "0.6.2", :git => "git@github.com:enmasse-entertainment/eme_global_assets.git"
gem "eme_global_assets", :path => "../eme_global_assets"

gem "activemodel", "~> 3.2.22.5"
gem "sinatra-support", "~> 1.2"
gem "compass", "~> 0.12"
gem "sass", "3.2.5"
gem "uglifier"

gem "sinatra-activerecord"
gem "mysql2", "0.3.18"


# added to coorect deploy issue
gem "net-ssh", "3.0.2"
gem 'executable-hooks', '1.3.2'

# UPGRADING THE FLASH
gem 'rack-flash3'
gem 'sinatra-redirect-with-flash'

gem "dalli", "2.6.0"
gem "thin", "1.6.1"

gem 'whenever', :require => false

gem 'unicorn'

gem "eme-ams-api-client", :git => "git@github.com:enmasse-entertainment/eme-ams-api-client.git", :require => 'ams_api_client'

gem 'httparty'
gem 'capistrano'
gem 'capistrano-rvm'
gem 'capistrano-bundler'
gem 'capistrano3-nginx', '2.1.4'
gem 'capistrano3-unicorn'
gem "eme-deploy", :branch => "update_cap34", :git => "git@github.com:enmasse-entertainment/eme-deploy.git"

group :development, :test do
  # automated testing libraries
  gem "rspec"
  gem "fakeweb"
  gem "capybara", "~> 2.0.3"
  gem "poltergeist"
  gem "watir-webdriver"
  gem "minitest"
  gem "minitest-reporters"
  gem "selenium-webdriver"
  gem "tmail"
  gem "nokogiri"
  gem "gmail"
  gem "tiny_tds"

  # libraries for reporting test results
  gem "simplecov", :require => false
  gem "simplecov-rcov", :require => false
  gem "sinatra-reloader"
  gem "debase"
  gem "ruby-debug-ide", "~> 0.7.0.beta7"
end

group :production, :edge, :qa do
  gem "airbrake", "~> 4.1.0"
  gem 'newrelic_rpm', '~> 6.2.0.354'
end
